In [1]:
# Importing liberaries
import numpy as np

# Indexing and Slicing

In [2]:
# create an array
a = np.array([1, 2, 3, 4, 5, 6, 7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
# from left to right
a[0]

1

In [12]:
a[1:]

array([2, 3, 4, 5, 6, 7])

In [13]:
# for range of values
a[1:5]

array([2, 3, 4, 5])

In [4]:
# from right to left
a[-1]

7

In [5]:
b = np.arange(0, 12, 2)
b

array([ 0,  2,  4,  6,  8, 10])

In [6]:
b[2]

4

In [14]:
c = b.reshape(3,2)
c

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [15]:
c[0]

array([0, 2])

In [16]:
c[0:2]

array([[0, 2],
       [4, 6]])

# Filtration

In [17]:
c[c <5]

array([0, 2, 4])

In [19]:
c[(c < 5) & (c > 7)] # as we know uf both coinditions are true then it will return our result

array([], dtype=int32)

In [21]:
c[(c < 5) | (c > 7)] # as we know uf any coinditions are true then it will return our result

array([ 0,  2,  4,  8, 10])

# Enlist Bolean or Conditional Operators

In Python, the following are the boolean or conditional operators:

1. `and`: Returns True if both statements are true
2. `or`: Returns True if one of the statements is true
3. `not`: Reverse the result, returns False if the result is true
4. `==`: Equal to
5. `!=`: Not equal to
6. `<`: Less than
7. `>`: Greater than
8. `<=`: Less than or equal to
9. `>=`: Greater than or equal to

Here's an example of how you might use these in a Python program:



In [23]:
x = 5
y = 3

# and operator : Returns `True`` if both conditions are True.
print(x > 3 and y < 4)  # Returns True because both conditions are true

# or operator : 	Returns True if at least one of the conditions is True.
print(x > 3 or y > 4)  # Returns True because one of the conditions is true

# not operator : 	Returns True if the condition is False and vice versa
print(not(x > 3 and y < 4))  # Returns False because the condition is true

# == operator : Returns `True` if the values on both sides are equal.
print(x == y)  # Returns False because 5 is not equal to 3

# != operator : Returns True if the values on both sides are not equal.
print(x != y)  # Returns True because 5 is not equal to 3

# < operator : Returns True if the left value is less than the right value.
print(x < y)  # Returns False because 5 is not less than 3

# > operator : Returns True if the left value is greater than the right value.
print(x > y)  # Returns True because 5 is greater than 3

# <= operator : Returns True if the left value is less than or equal to the right value.
print(x <= y)  # Returns False because 5 is not less than or equal to 3

# >= operator : Returns True if the left value is greater than or equal to the right value.
print(x >= y)  # Returns True because 5 is greater than or equal to 3

True
True
False
False
True
False
True
False
True
