In [2]:
# importing library
import numpy as np

# Making an Array from a data or another array

In [4]:
a = np.arange(0, 222, 5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [5]:
len(a)

45

In [7]:
array1 = a[40:45]
array1

array([200, 205, 210, 215, 220])

# Horizontal and Vertical Stack

In [8]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([8,9,10,11,12,13,14])

In [9]:
c = np.vstack((a,b))
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [11]:
d = np.hstack((a,b))    
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
d = d.reshape(2,7)
d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

# Spliting array into further smaller arrays

In [14]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [15]:
y = np.hsplit(x, 3)
y

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [16]:
z = np.hsplit(x, (3, 4))
z

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [18]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [20]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [21]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# if you want to copy an array

In [22]:
b2 = a.copy()
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
# for adding arrays
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [24]:
# for Subtraction
data - ones

array([0, 1])

In [25]:
# for multiplication
data * data

array([1, 4])

In [26]:
# for division
data / data

array([1., 1.])

In [27]:
# If you want to find the sum of the elements in an array
a = np.array([1, 2, 3, 4])
a.sum()

10

In [29]:
# To add the rows or the columns in a 2D array, you would specify the axis.
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [30]:
# You can sum over the axis of rows with
b.sum(axis=0)

array([3, 3])

In [31]:
# You can sum over the axis of columns with
b.sum(axis=1)

array([2, 4])