In [1]:
# Importing Liberary
import numpy as np

# Matrix or Matrices

In [3]:
# create a 2x3 matrix
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])    
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
# create a matrix of big dimension
b = np.arange(0, 100, 2).reshape(10, 5)
b

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [9]:
# create a matrix of big dimension
c = np.arange(0, 1000, 2).reshape(5, 100)
c

array([[  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
         26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
         52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
         78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
        104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
        130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
        156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
        182, 184, 186, 188, 190, 192, 194, 196, 198],
       [200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224,
        226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250,
        252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276,
        278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302,
        304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328,
        330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 35

In [10]:
# create a matrix of big dimension
b = np.arange(0, 100, 2).reshape(5, 10)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

# Slicing a Matrix

In [12]:
# slicing a matrix
b[1:3, 3:5]

array([[26, 28],
       [46, 48]])

In [29]:
b[2:4:, 5:7]

array([[50, 52],
       [70, 72]])

In [31]:
# slicing a matrix 3x2
c = b[0:3, 3:5]
c

array([[ 6,  8],
       [26, 28],
       [46, 48]])

In [34]:
# finding maximum value
b.max()

98

In [35]:
# finding minimum value
b.min()

0

In [37]:
# finding sum
b.sum()

2450

In [39]:
# for rows
b.min(axis=0)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [40]:
# for columns
b.min(axis=1)

array([ 0, 20, 40, 60, 80])

In [41]:
# for rows
b.max(axis=0)

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [42]:
# for columns
b.max(axis=1)

array([18, 38, 58, 78, 98])

In [45]:
m = np.arange(0, 20, 2).reshape(5, 2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [46]:
m + np.array([20, 22])

array([[20, 24],
       [24, 28],
       [28, 32],
       [32, 36],
       [36, 40]])

In [49]:
np.vstack((m, np.array([20, 22])))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22]])

# for reversing array or matrix

In [50]:
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [51]:
np.flip(b)

array([[98, 96, 94, 92, 90, 88, 86, 84, 82, 80],
       [78, 76, 74, 72, 70, 68, 66, 64, 62, 60],
       [58, 56, 54, 52, 50, 48, 46, 44, 42, 40],
       [38, 36, 34, 32, 30, 28, 26, 24, 22, 20],
       [18, 16, 14, 12, 10,  8,  6,  4,  2,  0]])