In [67]:
# Installing liberay
# pip install numpy

In [68]:
# Importing liberay
import numpy as np

# What is an array?

An array is a data structure that stores a collection of items. These items are stored at contiguous memory locations. The main features of an array are:

1. All elements in an array are of the same type, i.e., they have a common data type like int, char, etc.
2. The size of an array is fixed. It must be specified at the time of array declaration.
3. Elements in an array are accessed by their index. The index of the first element is 0, the second element is 1, and so on.

In the context of NumPy (which your file seems to be about), an array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [69]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [70]:
a.shape

(6,)

In [71]:
a2 = a[np.newaxis, :]
print(a2)

[[0 1 2 3 4 5]]


In [72]:

a2.shape

(1, 6)

In [73]:
#a2 = a[:, np.newaxis]
#print(a2)

In [74]:
a2.shape

(1, 6)

In [75]:
a3 = a2[np.newaxis, :]
print(a3)
a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

1D, 2D, and 3D arrays are used in data science for different purposes:

1. **1D Array**: A one-dimensional array is the simplest form of array, essentially a list of elements. It is used for simple operations like storing a sequence of values or performing mathematical operations on a sequence of numbers.

2. **2D Array**: A two-dimensional array is essentially a matrix. It is used for more complex operations that require a grid-like structure. For example, in image processing, images are often represented as 2D arrays where each cell represents a pixel. In tabular data, each row and column can be represented as a 2D array.

3. **3D Array**: A three-dimensional array can be thought of as an array of arrays of arrays. It is used in more complex scenarios. For example, in computer vision, a color image can be represented as a 3D array where the first dimension represents the height, the second dimension represents the width, and the third dimension represents the color channels (Red, Green, Blue).

In data science, these different types of arrays are used to handle different types of data. For example, time series data can be handled using 1D arrays, image data can be handled using 2D or 3D arrays, and so on. The choice of array dimensionality depends on the nature of the problem and the type of data you are working with.

# Creating Arrays with Numpy

In [76]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([(1, 2, 3, 4, 5, 6, 7), (4, 5, 6, 7, 8, 9, 10)])

In [77]:
type(a) # type of array

numpy.ndarray

In [78]:
a.dtype # data type of elements of array

dtype('int32')

In [79]:
b.dtype

dtype('int32')

In [80]:
print(a)
a.shape

[1 2 3 4 5 6 7]


(7,)

In [81]:
print(b)
b.shape

[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]


(2, 7)

# Initialize arrays

In [82]:
zeros = np.zeros((3, 4)) # rows and columns
zeros   

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [83]:
zeros.dtype

dtype('float64')

In [84]:
ones = np.ones((2, 5)) # rows and columns
ones 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [85]:
ones.dtype

dtype('float64')

In [86]:

full = np.full((2, 5), 5) # rows and columns
full

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [87]:
full.dtype

dtype('int32')

In [88]:
identity = np.eye(5) # Creating an identity matrix
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [89]:
identity.dtype

dtype('float64')

# Array Attributes

In [90]:

a.shape # give us the shape of array

(7,)

In [91]:
len(a) # give us the length of array

7

In [92]:
a.size # gives us the numbers of elements in array

7

In [93]:
a.ndim # Gives us the dimension of array

1

In [94]:
len(b) # give us the length of array

2

In [95]:
b.size # gives us the numbers of elements in array

14

In [96]:
b.ndim

2

In [97]:
identity.ndim

2

# Basic operaion

In [98]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [99]:
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [102]:
g = a - b # subtraction of two arrays
g

array([[ 0,  0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3, -3]])

In [103]:
g = b - a
g

array([[0, 0, 0, 0, 0, 0, 0],
       [3, 3, 3, 3, 3, 3, 3]])

In [104]:
# addition of two arrays
h = a + b
h

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [106]:
h1  = np.add(a, b)  # another method
h1 

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [107]:
# multiplication
i = a * b
i

array([[ 1,  4,  9, 16, 25, 36, 49],
       [ 4, 10, 18, 28, 40, 54, 70]])

In [108]:
# division
j = a / b
j

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
        0.66666667, 0.7       ]])

In [110]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [109]:
# square of each element
k = a ** 2
k

array([ 1,  4,  9, 16, 25, 36, 49])